const BAD_REQUEST = 400;
const NOT_FOUND = 404;
const INTERNAL_ERROR = 500;
const CREATED = 201;
const SUCCESS = 200;

module.exports = {
  BAD_REQUEST, NOT_FOUND, INTERNAL_ERROR, CREATED, SUCCESS,
};
